name: Deploy to Firebase

on:
  push:
    branches:
      - develop

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build project
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting (Live Channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TORANO_CLONE_BLUET52HZ }}
          channelId: live
          projectId: torano-clone-bluet52hz
